Add projects to fastdds
eProsima/DDS-Suite pull request #72
Opened 2023-04-04 15:10 UTC by jparisu

2023-04-11 13:49 UTC, jsantiago-eProsima requested changes, later dismissed

2023-04-11 13:49 UTC, jsan-rt commented on dds-suite.repos
> -    version: v2.9.1
Why the downgrade?

2023-04-12 18:49 UTC, EduPonz commented
CI with correct parameters:

[![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=dds_suite_ci&build=222)](http://jenkins.eprosima.com:8080/job/dds_suite_ci/222/)

2023-04-12 18:50 UTC, EduPonz approved these changes

2023-04-12 18:50 UTC, EduPonz approved these changes

2023-04-12 19:42 UTC, EduPonz commented
CI fails to publish result here as it was run manually, but the CI actually passed.

2023-04-12 19:42 UTC, merged